<?php

namespace PHPFUI\ORM\Record\Validation;

/**
 * Autogenerated. File will not be changed by subsequent runs of oneOffScripts\generateValidators.php.  Delete and rerun if you want.
 */
class Migration extends \PHPFUI\ORM\Validator
	{
	/** @var array<string, string[]> */
	public static array $validators = [
		'ran' => ['required', 'datetime'],
	];

	public function __construct(\PHPFUI\ORM\Record\Migration $record)
		{
		parent::__construct($record);
		}
	}
