<?php

namespace PHPFUI\ORM\Record\Validation;

/**
 * Autogenerated. Do not modify. Modify SQL table, then run oneOffScripts\generateValidators.php table_name
 */
class Migration extends \PHPFUI\ORM\Validator
	{
	/** @var array<string, string[]> */
	public static array $validators = [
		'ran' => ['required', 'datetime'],
	];

	public function __construct(\PHPFUI\ORM\Record\Migration $record)
		{
		parent::__construct($record);
		}
	}
