<?php

namespace PHPFUI\ORM\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property int $migrationId MySQL type int
 * @property \PHPFUI\ORM\Record\Migration $migration related record
 * @property string $ran MySQL type datetime
 */
abstract class Migration extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = false;

	/** @var array<string, \PHPFUI\ORM\FieldDefinition> */
	protected static array $fields = [];

	/** @var array<string> */
	protected static array $primaryKeys = ['migrationId', ];

	protected static string $table = 'migration';

	public function initFieldDefinitions() : static
		{
		if (! \count(static::$fields))
			{
			static::$fields = [
				'migrationId' => new \PHPFUI\ORM\FieldDefinition('int', 'int', 0, false, ),
				'ran' => new \PHPFUI\ORM\FieldDefinition('datetime', 'string', 20, false, 'CURRENT_TIMESTAMP', ),
			];
			}

		return $this;
		}
	}
