<?php

namespace PHPFUI\ORM\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then run oneOffScripts\generateCRUD.php table_name
 *
 * @property int $migrationId MySQL type int(11)
 * @property \PHPFUI\ORM\Record\Migration $migration related record
 * @property string $ran MySQL type timestamp
 */
abstract class Migration extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = false;

	/** @var array<string, \PHPFUI\ORM\FieldDefinition> */
	protected static array $fields = [];

	/** @var array<string> */
	protected static array $primaryKeys = ['migrationId', ];

	protected static string $table = 'migration';

	public function initFieldDefinitions() : static
		{
		if (! \count(static::$fields))
			{
			static::$fields = [
				'migrationId' => new \PHPFUI\ORM\FieldDefinition('int(11)', 'int', 11, false, null, ),
				'ran' => new \PHPFUI\ORM\FieldDefinition('timestamp', 'string', 20, false, null, ),
			];
			}

		return $this;
		}
	}
