<?php

namespace Tests\Fixtures\Record\Validation;

/**
 * Autogenerated. File will not be changed by oneOffScripts\generateValidators.php.  Delete and rerun if you want.
 */
class OrderDetail extends \PHPFUI\ORM\Validator
	{
	/** @var array<string, string[]> */
	public static array $validators = [
		'date_allocated' => ['maxlength', 'datetime'],
		'discount' => ['required', 'number'],
		'inventory_transaction_id' => ['integer'],
		'order_detail_id' => ['integer'],
		'order_detail_status_id' => ['integer'],
		'order_id' => ['required', 'integer'],
		'product_id' => ['integer'],
		'purchase_order_id' => ['integer'],
		'quantity' => ['required', 'number'],
		'unit_price' => ['number'],
		];
	}
