<?php

namespace Tests\Fixtures\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property ?string $attachments MySQL type longblob
 * @property ?string $category MySQL type varchar(50)
 * @property ?string $description MySQL type longtext
 * @property int $discontinued MySQL type integer
 * @property float $list_price MySQL type decimal(19,4)
 * @property ?int $minimum_reorder_quantity MySQL type integer
 * @property ?string $product_code MySQL type varchar(25)
 * @property int $product_id MySQL type integer
 * @property \Tests\App\Record\Product $product_ related record
 * @property ?string $product_name MySQL type varchar(50)
 * @property ?string $quantity_per_unit MySQL type varchar(50)
 * @property ?int $reorder_level MySQL type integer
 * @property ?float $standard_cost MySQL type decimal(19,4)
 * @property ?int $target_level MySQL type integer
 */
abstract class Product extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = true;

	/** @var array<string, array<mixed>> */
	protected static array $fields = [
		// MYSQL_TYPE, PHP_TYPE, LENGTH, NULL, DEFAULT, KEY
		'attachments' => ['longblob', 'string', 0, true, null, false, ],
		'category' => ['varchar(50)', 'string', 50, true, null, false, ],
		'description' => ['longtext', 'string', 4294967295, true, null, false, ],
		'discontinued' => ['integer', 'int', 0, false, 0, false, ],
		'list_price' => ['decimal(19,4)', 'float', 19, false, 0, false, ],
		'minimum_reorder_quantity' => ['integer', 'int', 0, true, null, false, ],
		'product_code' => ['varchar(25)', 'string', 25, true, null, false, ],
		'product_id' => ['integer', 'int', 0, false, null, true, ],
		'product_name' => ['varchar(50)', 'string', 50, true, null, false, ],
		'quantity_per_unit' => ['varchar(50)', 'string', 50, true, null, false, ],
		'reorder_level' => ['integer', 'int', 0, true, null, false, ],
		'standard_cost' => ['decimal(19,4)', 'float', 19, true, 0, false, ],
		'target_level' => ['integer', 'int', 0, true, null, false, ],
	];

	/** @var array<string, true> */
	protected static array $primaryKeys = ['product_id' => true, ];

	protected static string $table = 'product';
	}
