<?php

namespace Tests\Fixtures\Record\Definition;

/**
 * Autogenerated. Do not modify. Modify SQL table, then generate with \PHPFUI\ORM\Tool\Generate\CRUD class.
 *
 * @property ?string $date_received MySQL type datetime
 * @property ?int $inventory_transaction_id MySQL type int
 * @property \Tests\App\Record\InventoryTransaction $inventory_transaction related record
 * @property int $posted_to_inventory MySQL type int
 * @property ?int $product_id MySQL type int
 * @property \Tests\App\Record\Product $product related record
 * @property int $purchase_order_detail_id MySQL type int
 * @property int $purchase_order_id MySQL type int
 * @property \Tests\App\Record\PurchaseOrder $purchase_order related record
 * @property float $quantity MySQL type decimal(18,4)
 * @property float $unit_cost MySQL type decimal(19,4)
 */
abstract class PurchaseOrderDetail extends \PHPFUI\ORM\Record
	{
	protected static bool $autoIncrement = true;

	/** @var array<string, \PHPFUI\ORM\FieldDefinition> */
	protected static array $fields = [];

	/** @var array<string> */
	protected static array $primaryKeys = ['purchase_order_detail_id', ];

	protected static string $table = 'purchase_order_detail';

	public function initFieldDefinitions() : static
		{
		if (! \count(static::$fields))
			{
			static::$fields = [
				'date_received' => new \PHPFUI\ORM\FieldDefinition('datetime', 'string', 20, true, ),
				'inventory_transaction_id' => new \PHPFUI\ORM\FieldDefinition('int', 'int', 0, true, ),
				'posted_to_inventory' => new \PHPFUI\ORM\FieldDefinition('int', 'int', 0, false, 0, ),
				'product_id' => new \PHPFUI\ORM\FieldDefinition('int', 'int', 0, true, ),
				'purchase_order_detail_id' => new \PHPFUI\ORM\FieldDefinition('int', 'int', 0, false, ),
				'purchase_order_id' => new \PHPFUI\ORM\FieldDefinition('int', 'int', 0, false, ),
				'quantity' => new \PHPFUI\ORM\FieldDefinition('decimal(18,4)', 'float', 19, false, ),
				'unit_cost' => new \PHPFUI\ORM\FieldDefinition('decimal(19,4)', 'float', 20, false, ),
			];
			}

		return $this;
		}
	}
